### ISSUE TITLE
Some frames new annotations keep unchange

### ISSUE THREAD

**Issue by luckyyf0517** [zlw9161/CARRADA-RAC#1]
Thank you for your work to solve my confusion about the inaccurate annotation of Carrada dataset. But why when i use the new pipeline, some frames have the new annotation, while some frames remain the same or just change a little. (sorry I didn't have time to read the pipeline code carefully)

Here is a simple example (left is the old dataset, and the right is the new dataset with new annotation)

![image](https://github.com/zlw9161/CARRADA-RAC/assets/108784091/4bae29b3-c360-4f14-baed-b95d4ed36919)

**Comment by zlw9161** [comment]
Thx for noticing our work, could you pls check the original rd or ra signals? Our pipeline relies more on the CFAR results compared to the original CARRADA pipeline, not only the image captured by the camera, i.e., pays more attention on the radar. Please check the appendix we attached on the PKC code link.



Liwen Zhang

Harbin Institute of Technology, China, CS PhD
Tel: +86 15739528601 / 15510600601
E-mail: ***@***.*** / ***@***.***
---- Replied Message ----
| From | ***@***.***> |
| Date | 4/10/2024 12:03 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [zlw9161/CARRADA-RAC] Some frames new annotations keep unchange (Issue #1) |

Thank you for your work to solve my confusion about the inaccurate annotation of Carrada dataset. But why when i use the new pipeline, some frames have the new annotation, while some frames remain the same or just change a little. (sorry I didn't have time to read the pipeline code carefully)

Here is a simple example

image.png (view on web)

**Comment by luckyyf0517** [comment]
Thanks for your reply. 

I performed the new pipeline you provided on the original carrada dataset, I think the ra and rd data are no problem. 

If it works, the new annotations generated by the new pipeline should be a big improvement over the original Carrada annotations, right, rather than a lot of frames without significant improvement as in my run. If that's the case, I'll check it out again.

Looking forward to your reply.

**Comment by zlw9161** [comment]
U R right, not all the original annotations are fixed in our pipeline, after all it is the automatic annotation method, the ground truths are not available for neither CARRADA or CARRADA-RAC. You can directly train the segmentation model to verify the improvement of our annotations, which can bring improvement for the segmentatiuon models.

**Comment by zlw9161** [comment]
> Thanks for your reply.
> 
> I performed the new pipeline you provided on the original carrada dataset, I think the ra and rd data are no problem.
> 
> If it works, the new annotations generated by the new pipeline should be a big improvement over the original Carrada annotations, right, rather than a lot of frames without significant improvement as in my run. If that's the case, I'll check it out again.
> 
> Looking forward to your reply.

U R right, not all the original annotations are fixed in our pipeline, after all it is the automatic annotation method, the ground truths are not available for neither CARRADA or CARRADA-RAC. You can directly train the segmentation model to verify the improvement of our annotations, which can bring improvement for the segmentatiuon models.
